package main

import (
	"bufio"
	"bytes"
	"encoding/hex"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/rlp"
)

type host struct {
	Name string
	IP   string
}

// qbftExtraData matches the QBFT genesis extra data structure:
//
//	RLP([vanity, [validators...], vote, round, [seals]])
//
// For genesis: vote = empty list, round = 0, seals = empty list.
type qbftExtraData struct {
	Vanity     [32]byte
	Validators []common.Address
	Vote       [][]byte
	Round      uint32
	Seals      [][]byte
}

func main() {
	inventory := flag.String("inventory", "", "Path to Ansible inventory.ini")
	roleDir := flag.String("role-dir", "", "Path to ansible-role-besu directory")
	p2pPort := flag.Int("p2p-port", 40111, "P2P port for enode URLs")
	flag.Parse()

	if *inventory == "" || *roleDir == "" {
		fmt.Fprintln(os.Stderr, "Usage: besu-keygen --inventory PATH --role-dir PATH [--p2p-port PORT]")
		os.Exit(1)
	}

	hosts, err := parseInventory(*inventory)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to parse inventory: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Found %d hosts in inventory\n", len(hosts))

	var validators []common.Address
	var enodes []string

	for _, h := range hosts {
		key, err := crypto.GenerateKey()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to generate key for %s: %v\n", h.Name, err)
			os.Exit(1)
		}

		privKeyHex := hex.EncodeToString(crypto.FromECDSA(key))
		pubKey := crypto.FromECDSAPub(&key.PublicKey)
		pubKeyHex := hex.EncodeToString(pubKey[1:]) // strip 0x04 prefix
		addr := crypto.PubkeyToAddress(key.PublicKey)

		validators = append(validators, addr)
		enodes = append(enodes, fmt.Sprintf("enode://%s@%s:%d", pubKeyHex, h.IP, *p2pPort))

		// Write nodekey to role files directory
		keyDir := filepath.Join(*roleDir, "files", "keys", h.Name)
		if err := os.MkdirAll(keyDir, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to create directory %s: %v\n", keyDir, err)
			os.Exit(1)
		}
		if err := os.WriteFile(filepath.Join(keyDir, "nodekey"), []byte(privKeyHex), 0600); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to write nodekey for %s: %v\n", h.Name, err)
			os.Exit(1)
		}
		if err := os.WriteFile(filepath.Join(keyDir, "address"), []byte(hex.EncodeToString(addr.Bytes())), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to write address for %s: %v\n", h.Name, err)
			os.Exit(1)
		}

		fmt.Printf("  %s: address=0x%s\n", h.Name, hex.EncodeToString(addr.Bytes()))
	}

	// Encode QBFT extraData with all validator addresses
	extraData, err := encodeQBFTExtraData(validators)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to encode extraData: %v\n", err)
		os.Exit(1)
	}
	extraDataHex := "0x" + hex.EncodeToString(extraData)

	// Write group_vars for the besu group
	groupVarsDir := filepath.Join(*roleDir, "test", "group_vars", "besu")
	if err := os.MkdirAll(groupVarsDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create group_vars directory: %v\n", err)
		os.Exit(1)
	}

	var yamlBuf strings.Builder
	yamlBuf.WriteString("---\n")
	yamlBuf.WriteString("# Generated by besu-keygen — DO NOT EDIT\n")
	yamlBuf.WriteString(fmt.Sprintf("besu_genesis_extradata: \"%s\"\n", extraDataHex))
	yamlBuf.WriteString("besu_bootnodes:\n")
	for _, e := range enodes {
		yamlBuf.WriteString(fmt.Sprintf("  - \"%s\"\n", e))
	}

	groupVarsPath := filepath.Join(groupVarsDir, "network.yml")
	if err := os.WriteFile(groupVarsPath, []byte(yamlBuf.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write group_vars: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("\nGenerated:\n")
	fmt.Printf("  extraData: %s\n", extraDataHex)
	fmt.Printf("  bootnodes: %d entries\n", len(enodes))
	fmt.Printf("  group_vars: %s\n", groupVarsPath)
	fmt.Printf("  node keys: %s/files/keys/*/nodekey\n", *roleDir)
}

// parseInventory reads an Ansible INI inventory and returns hosts from the
// [validator] section.
func parseInventory(path string) ([]host, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var hosts []host
	inValidators := false
	re := regexp.MustCompile(`^(\S+)\s+ansible_host=(\S+)`)

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		if line == "[validator]" || line == "[validators]" {
			inValidators = true
			continue
		}
		if strings.HasPrefix(line, "[") {
			inValidators = false
			continue
		}
		if !inValidators || line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		matches := re.FindStringSubmatch(line)
		if matches != nil {
			hosts = append(hosts, host{Name: matches[1], IP: matches[2]})
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if len(hosts) == 0 {
		return nil, fmt.Errorf("no hosts found in [validator] or [validators] section")
	}

	return hosts, nil
}

// encodeQBFTExtraData RLP-encodes the QBFT genesis extra data with the given
// validator addresses. Validators are sorted ascending by address as required
// by the QBFT protocol.
func encodeQBFTExtraData(validators []common.Address) ([]byte, error) {
	sort.Slice(validators, func(i, j int) bool {
		return bytes.Compare(validators[i].Bytes(), validators[j].Bytes()) < 0
	})

	extra := qbftExtraData{
		Vanity:     [32]byte{},
		Validators: validators,
		Vote:       [][]byte{},
		Round:      0,
		Seals:      [][]byte{},
	}

	return rlp.EncodeToBytes(extra)
}
